output_root: '../outputs'
pytorch_data_dir: '/datadrive/pytorch-data/'
experiment_name: "exp1"
res: 320
batch_size: 4
num_workers: 4
run_picie: False
run_crf: False
run_prediction: True
dark_mode: True
use_ddp: False

model_paths:
  # - "../saved_models/cocostuff27_vit_base_5.ckpt"
  #- "../saved_models/cityscapes_vit_base_1.ckpt"
  #- "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
